### ISSUE TITLE
Second assingment data

### ISSUE THREAD

**Issue by sirkaq** [alexanderquispe/Diplomado_PUCP#47]
Anzony,porfa, podrías precisar qué modulos y año de la ENAPRES debemos usar para este ejercicio. No usé anteriormente esta base de datos.
Muchas gracias

**Comment by anzonyquispe** [comment]
Hi @sirkaq,

Please ask it again in the main issue. This is the link of the main [issue](https://github.com/alexanderquispe/Diplomado_PUCP/issues/44).

**Comment by sirkaq** [comment]
Hi @anzonyquispe . Don't worry. It was a confusion that I've resolved yet. Next time I'm going to write in the right place.
