### ISSUE TITLE
Add email - group 12

### ISSUE THREAD

**Issue by jbenitesg** [alexanderquispe/Diplomado_PUCP#507]
Hi group 12, @isaisilva12 @Claudiaf-174 @MichaelSuarez0 
Please include your email and full names in your songs on the script [Fav_songs_G12](https://github.com/alexanderquispe/Diplomado_PUCP/commit/ca50a1de290f67246190667aeee66a4eef2da7dc) and request the review.

**Comment by MichaelSuarez0** [comment]
Hi, I already added my email and full name. Please review

**Comment by isaisilva12** [comment]
Hi, I already added my email and full name. Please review

**Comment by Claudiaf-174** [comment]
Hi, I already added my email and full name. Please review

**Comment by jbenitesg** [comment]
Hi @Claudiaf-174 @MichaelSuarez0 @isaisilva12  all submissions have been reviewed and sent to the main repo
