### ISSUE TITLE
UnicodeDecodeError using sav.SavHeaderReader

### ISSUE THREAD

**Issue by anzonyquispe** [alexanderquispe/Diplomado_PUCP#54]
We try to solve this problem `"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 77: invalid continuation byte"` with sav.SavHeaderReader.

**Comment by anzonyquispe** [comment]
Hi @lopezluzmila , 

You can import the files using pandas. When you tried to import using SavHeaderReader, did you opened the SAV file using SPSS?

**Comment by lopezluzmila** [comment]
> We try to solve this problem `"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 77: invalid continuation byte"` with sav.SavHeaderReader.

Hi again Anzony!
I can open REC0111.sav, RE223132.sav and RE516171.sav when I use pd.read_spss
![image](https://user-images.githubusercontent.com/94266695/143481862-a304b3f7-ab80-4f55-a0f8-fb18df0963a8.png)

**Comment by anzonyquispe** [comment]
There is no problem with Pandas. Please, send me an email to schedule a meeting to solve this problem.

**Comment by anzonyquispe** [comment]
We could not solve the issue with , but we decided to use a different library. It works for @lopezluzmila and @hansaguirre1 

`pip install pyreadstat`
`import pyreadstat`
`rec1, meta = pyreadstat.read_sav( r"../../_data/endes/2019/REC0111.sav" )`
`value_labels = meta.variable_value_labels`
`var_labels = meta.column_names_to_labels`
